[project]
name = "aap-gateway"
authors = [{ name = "Red Hat, Inc.", email = "info@ansible.com" }]
description = "Ansible Automation Platform gateway"
readme = "README.md"
requires-python = ">=3.9"
keywords = ["ansible", "django", "gateway"]
license = { text = "Apache-2.0" }
classifiers = [
  "Framework :: Django",
  "Development Status :: 5 - Production/Stable",
  "Environment :: Web Environment",
  "Framework :: Django",
  "Intended Audience :: Developers",
  "Intended Audience :: System Administrators",
  "Operating System :: OS Independent",
  "License :: OSI Approved :: Apache Software License",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
]
dynamic = ["version", "dependencies"]


[tool.setuptools.dynamic]
dependencies = { file = [
  "requirements/requirements.in",
  "requirements/requirements_git.txt",
] }
version = { attr = "aap_gateway_api.__version__" }


[tool.setuptools.packages.find]
include = ["aap_gateway_api*"]
exclude = ["aap_gateway_api.tests*"]

[tool.setuptools.package-data]
"aap_gateway_api.templates" = ["**"]
"aap_gateway_api.static" = ["**"]

[build-system]
requires = ["setuptools>=64", "setuptools_scm>=8,<9"]
build-backend = 'setuptools.build_meta'

[project.scripts]
aap-gateway-manage = "aap_gateway_api:manage"

[tool.black]
line-length = 160
fast = true
skip-string-normalization = true
force-exclude = '''
(
   .*/migrations/
 | aap-dev/*
)
'''

[tool.isort]
profile = "black"
line_length = 160
extend_skip = ["aap_gateway_api/migrations", "django-ansible-base", "aap-dev", "services"]

[tool.flake8]
max-line-length = 160
extend-ignore = ["E203"]
exclude = ['aap_gateway_api/migrations/*', '.tox', 'django-ansible-base', 'aap-dev/*', 'services/*']
# E402: module level import not at top of file. Ansible modules follow a
# somewhat different convention here because DOCUMENTATION, EXAMPLES, and
# RETRUN module variables contain documentation.
per-file-ignores = """
    ansible_platform_collection/plugins/modules/*:E402
"""

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "aap_gateway_api.tests.settings_overrides"
addopts = "--strict-markers --reuse-db --create-db --migrations -s -vvv"
pythonpath = ". aap_gateway_api"
markers = [
]

[tool.tox]
legacy_tox_ini = """
    [tox]
    min_version = 4.0
    no_package = true
    env_list =
        check
        check-migrations
        check-oauth2-permissions
        check-help-text
        py311
    labels =
        test = py311
        check = check, check-migrations, check-oauth2-permissions, check-help-text
        lint = flake8, black, isort

    [docker:db]
    dockerfile = {toxinidir}/tools/dev_postgres/Dockerfile
    expose =
        DB_PORT=5432/tcp

    [testenv]
    allowlist_externals = ./tools/scripts/ci/tox-reinstall-django-ansible-base.sh
    docker = db
    setenv =
        PYTHONPATH = {toxinidir}/django-ansible-base/
        GATEWAY_SECRET_KEY_FILE = {toxinidir}/tools/configs/dev_secret_key
    passenv = ANSIBLE_GW_TEST_DB_HOST
    deps =
        -r{toxinidir}/requirements/requirements.txt
        -r{toxinidir}/requirements/requirements_git.txt
        -r{toxinidir}/requirements/requirements_test.txt
        django-debug-toolbar==5.2  # Required to install for unit tests
        psycopg[binary]
    commands =
        ./tools/scripts/ci/tox-reinstall-django-ansible-base.sh {envname}
        pytest -n {env:PYTEST_NUM_PROCESSES:auto} --cov=. --cov-report=xml:coverage.xml --cov-report=html --cov-report=json --cov-branch --junit-xml=aap-gateway-test-results.xml {env:GATEWAY_TEST_DIRS:aap_gateway_api/tests} {posargs}

    [testenv:check]
    allowlist_externals = ./tools/scripts/ci/tox-reinstall-django-ansible-base.sh
    setenv =
        PYTHONPATH = {toxinidir}:{toxinidir}/django-ansible-base/
        GATEWAY_SECRET_KEY_FILE = {toxinidir}/tools/configs/dev_secret_key
        DATABASE_ENGINE = django.db.backends.dummy
    deps =
        -r{toxinidir}/requirements/requirements.txt
        -r{toxinidir}/requirements/requirements_git.txt
        -r{toxinidir}/requirements/requirements_test.txt
        psycopg[binary]
    commands =
        ./tools/scripts/ci/tox-reinstall-django-ansible-base.sh {envname}
        python3 -m aap_gateway_api check

    [testenv:check-migrations]
    allowlist_externals = ./tools/scripts/ci/tox-reinstall-django-ansible-base.sh
    setenv =
        PYTHONPATH = {toxinidir}:{toxinidir}/django-ansible-base/
        GATEWAY_SECRET_KEY_FILE = {toxinidir}/tools/configs/dev_secret_key
        DATABASE_ENGINE = django.db.backends.dummy
    deps =
        -r{toxinidir}/requirements/requirements.txt
        -r{toxinidir}/requirements/requirements_git.txt
        -r{toxinidir}/requirements/requirements_test.txt
         psycopg[binary]
    commands =
        ./tools/scripts/ci/tox-reinstall-django-ansible-base.sh {envname}
        python3 -m aap_gateway_api makemigrations --check

    [testenv:check-oauth2-permissions]
    allowlist_externals = ./tools/scripts/ci/tox-reinstall-django-ansible-base.sh
    setenv =
        PYTHONPATH = {toxinidir}:{toxinidir}/django-ansible-base/
        GATEWAY_SECRET_KEY_FILE = {toxinidir}/tools/configs/dev_secret_key
        DATABASE_ENGINE = django.db.backends.dummy
    deps =
        -r{toxinidir}/requirements/requirements.txt
        -r{toxinidir}/requirements/requirements_git.txt
        -r{toxinidir}/requirements/requirements_test.txt
        psycopg[binary]
    commands =
        ./tools/scripts/ci/tox-reinstall-django-ansible-base.sh {envname}
        python3 -m aap_gateway_api check --deploy --tag oauth2_permissions

    [testenv:check-help-text]
    allowlist_externals = ./tools/scripts/ci/tox-reinstall-django-ansible-base.sh
    setenv =
        PYTHONPATH = {toxinidir}:{toxinidir}/django-ansible-base/
        GATEWAY_SECRET_KEY_FILE = {toxinidir}/tools/configs/dev_secret_key
        DATABASE_ENGINE = django.db.backends.dummy
    deps =
        -r{toxinidir}/requirements/requirements.txt
        -r{toxinidir}/requirements/requirements_git.txt
        -r{toxinidir}/requirements/requirements_test.txt
        psycopg[binary]
    commands =
        ./tools/scripts/ci/tox-reinstall-django-ansible-base.sh {envname}
        python3 -m aap_gateway_api help_text_check --applications=aap_gateway_api --ignore-file ./.help_text_check.ignore

    [testenv:flake8]
    deps =
        flake8==7.1.1
        Flake8-pyproject==1.2.3
    docker =
    commands = flake8 {posargs:.}

    [testenv:black]
    deps =
        black==25.1.0
    docker =
    commands = black {posargs:.}

    [testenv:isort]
    deps =
        isort==6.0.0
    docker =
    commands = isort {posargs:.}

    [testenv:check-lint]
    # allowlist_externals = bash
    deps =
        flake8==7.1.1
        Flake8-pyproject==1.2.3
        black==25.1.0
        isort==6.0.0
    docker =
    commands =
        # bash -c "black --check . || flake8 . || isort --check ."
        black --check .
        flake8 .
        isort --check .
"""

[tool.coverage.run]
omit = ["aap_gateway_api/tests/*", "django-ansible-base/*"]
relative_files = true
