[project]
name = "aap-gateway"
authors = [{ name = "Red Hat, Inc.", email = "info@ansible.com" }]
description = "Ansible Automation Platform gateway"
readme = "README.md"
requires-python = ">=3.11"
keywords = ["ansible", "django", "gateway"]
license = { text = "Apache-2.0" }
classifiers = [
  "Framework :: Django",
  "Development Status :: 5 - Production/Stable",
  "Environment :: Web Environment",
  "Framework :: Django",
  "Intended Audience :: Developers",
  "Intended Audience :: System Administrators",
  "Operating System :: OS Independent",
  "License :: OSI Approved :: Apache Software License",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
]
dynamic = ["version", "dependencies"]


[tool.setuptools.dynamic]
dependencies = { file = [
  "requirements/requirements.in",
  "requirements/requirements_git.txt",
] }
version = { attr = "aap_gateway_api.__version__" }


[tool.setuptools.packages.find]
include = ["aap_gateway_api*"]
exclude = ["aap_gateway_api.tests*"]

[tool.setuptools.package-data]
"aap_gateway_api.templates" = ["**"]
"aap_gateway_api.static" = ["**"]

[build-system]
requires = ["setuptools>=64", "setuptools_scm>=8,<9"]
build-backend = 'setuptools.build_meta'

[project.scripts]
aap-gateway-manage = "aap_gateway_api:manage"

[tool.black]
line-length = 160
fast = true
skip-string-normalization = true
force-exclude = '''
(
   .*/migrations/
 | aap-dev/*
)
'''

[tool.isort]
profile = "black"
line_length = 160
extend_skip = ["aap_gateway_api/migrations", "django-ansible-base", "aap-dev", "services"]

[tool.flake8]
max-line-length = 160
extend-ignore = ["E203"]
exclude = ['aap_gateway_api/migrations/*', '.tox', 'django-ansible-base', 'aap-dev/*', 'services/*']

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "aap_gateway_api.tests.settings_overrides"
addopts = "--strict-markers --reuse-db --create-db --migrations -s -vvv"
pythonpath = ". aap_gateway_api"
markers = [
]

[tool.tox]
legacy_tox_ini = """
    [tox]
    min_version = 4.0
    no_package = true
    env_list =
        check
        check-migrations
        check-oauth2-permissions
        check-help-text
        py312
        312
        py311
        311
        black
        flake8
        isort
        check-lint

    labels =
        test = py312
        312 = py312
        311 = py311
        check = check, check-migrations, check-oauth2-permissions, check-help-text
        lint = flake8, black, isort

    [docker:db]
    ## NOTE: If you see this failing with output as shown below, 
    ## apply a patch from the PR link to the last file listed.
    ## ---------------------------------------------------
    ## File ".../site-packages/tox_docker/plugin.py", line 53, in get_gateway_ip
    ##     ip = container.attrs["NetworkSettings"]["Gateway"] or "0.0.0.0"
    ##          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
    ## KeyError: 'Gateway'
    ## ---------------------------------------------------
    ## Patch from PR: https://patch-diff.githubusercontent.com/raw/tox-dev/tox-docker/pull/196.patch

    image = quay.io/sclorg/postgresql-15-c9s
    environment =
        POSTGRESQL_PASSWORD=password
        POSTGRESQL_ADMIN_PASSWORD=password
        POSTGRESQL_USER=gw
        POSTGRESQL_DATABASE=gw_db
    healthcheck_cmd = PGPASSWORD=$POSTGRESQL_PASSWORD psql \
        --user=$POSTGRESQL_USER --dbname=$POSTGRESQL_DATABASE \
        --host=127.0.0.1 --quiet --no-align --tuples-only \
        -1 --command="SELECT 1"
    healthcheck_timeout = 5
    healthcheck_retries = 5
    healthcheck_interval = 10
    healthcheck_start_period = 3
    expose =
        DB_PORT=5432/tcp
    host_var = ANSIBLE_GW_TEST_DB_HOST

    [testenv]
    deps =
        -r{toxinidir}/requirements/requirements_test.txt

    [testenv:py311,py312]
    allowlist_externals =
        ./tools/scripts/ci/tox-reinstall-django-ansible-base.sh
        ./tools/scripts/ci/install_django_venv.sh
        pytest
    docker = db
    passenv = 
        ANSIBLE_GW_TEST_DB_HOST
        DB_PORT
    setenv =
        PYTHONPATH = {toxinidir}/django-ansible-base/
        GATEWAY_SECRET_KEY_FILE = {toxinidir}/tools/configs/dev_secret_key
    install_command = ./tools/scripts/ci/install_django_venv.sh {envname} {opts} {packages}
    commands =
        ./tools/scripts/ci/tox-reinstall-django-ansible-base.sh {envname}
        pytest -n {env:PYTEST_NUM_PROCESSES:auto} --cov=. --cov-report=xml:coverage.xml --cov-report=html --cov-report=json --cov-branch --junit-xml=aap-gateway-test-results.xml {env:GATEWAY_TEST_DIRS:aap_gateway_api/tests} {posargs}

    [testenv:check]
    allowlist_externals =
        ./tools/scripts/ci/tox-reinstall-django-ansible-base.sh
        ./tools/scripts/ci/install_django_venv.sh
    setenv =
        PYTHONPATH = {toxinidir}:{toxinidir}/django-ansible-base/
        GATEWAY_SECRET_KEY_FILE = {toxinidir}/tools/configs/dev_secret_key
        DATABASE_ENGINE = django.db.backends.dummy
    deps =
        -r{toxinidir}/requirements/requirements.txt
        -r{toxinidir}/requirements/requirements_git.txt
        -r{toxinidir}/requirements/requirements_test.txt
        psycopg[binary]
    commands =
        ./tools/scripts/ci/tox-reinstall-django-ansible-base.sh {envname}
        python3 -m aap_gateway_api check

    [testenv:check-migrations]
    allowlist_externals =
        ./tools/scripts/ci/tox-reinstall-django-ansible-base.sh
        ./tools/scripts/ci/install_django_venv.sh
    setenv =
        PYTHONPATH = {toxinidir}:{toxinidir}/django-ansible-base/
        GATEWAY_SECRET_KEY_FILE = {toxinidir}/tools/configs/dev_secret_key
        DATABASE_ENGINE = django.db.backends.dummy
    deps =
        -r{toxinidir}/requirements/requirements.txt
        -r{toxinidir}/requirements/requirements_git.txt
        -r{toxinidir}/requirements/requirements_test.txt
         psycopg[binary]
    commands =
        ./tools/scripts/ci/tox-reinstall-django-ansible-base.sh {envname}
        python3 -m aap_gateway_api makemigrations --check

    [testenv:check-oauth2-permissions]
    allowlist_externals =
        ./tools/scripts/ci/tox-reinstall-django-ansible-base.sh
        ./tools/scripts/ci/install_django_venv.sh
    setenv =
        PYTHONPATH = {toxinidir}:{toxinidir}/django-ansible-base/
        GATEWAY_SECRET_KEY_FILE = {toxinidir}/tools/configs/dev_secret_key
        DATABASE_ENGINE = django.db.backends.dummy
    deps =
        -r{toxinidir}/requirements/requirements.txt
        -r{toxinidir}/requirements/requirements_git.txt
        -r{toxinidir}/requirements/requirements_test.txt
        psycopg[binary]
    commands =
        ./tools/scripts/ci/tox-reinstall-django-ansible-base.sh {envname}
        python3 -m aap_gateway_api check --deploy --tag oauth2_permissions

    [testenv:check-help-text]
    allowlist_externals =
        ./tools/scripts/ci/tox-reinstall-django-ansible-base.sh
        ./tools/scripts/ci/install_django_venv.sh
    setenv =
        PYTHONPATH = {toxinidir}:{toxinidir}/django-ansible-base/
        GATEWAY_SECRET_KEY_FILE = {toxinidir}/tools/configs/dev_secret_key
        DATABASE_ENGINE = django.db.backends.dummy
    install_command = ./tools/scripts/ci/install_django_venv.sh {envname} {opts} {packages}
    commands =
        ./tools/scripts/ci/tox-reinstall-django-ansible-base.sh {envname}
        python3 -m aap_gateway_api help_text_check --applications=aap_gateway_api --ignore-file ./.help_text_check.ignore

    [testenv:flake8]
    allowlist_externals = flake8
    install_command = pip install {opts} {packages}
    commands = flake8 {posargs:.}

    [testenv:black]
    allowlist_externals = black
    install_command = pip install {opts} {packages}
    commands = black {posargs:.}

    [testenv:isort]
    allowlist_externals = isort
    install_command = pip install {opts} {packages}
    commands = isort {posargs:.}

    [testenv:check-lint]
    allowlist_externals =
        black
        flake8
        isort
    install_command = pip install {opts} {packages}
    commands =
        black --check .
        flake8 .
        isort --check .
"""

[tool.coverage.run]
omit = ["aap_gateway_api/tests/*", "django-ansible-base/*"]
relative_files = true
