# Generated by Claude Code (claude-sonnet-4@20250514)
import pytest
from ansible_base.lib.utils.response import get_relative_url
from ansible_base.rbac.models import DABContentType, DABPermission, RoleDefinition
from rest_framework.exceptions import ValidationError

from aap_gateway_api.views.api.v1.role import GatewayRoleDefinitionSerializer


@pytest.fixture
def galaxy_content_type():
    """Create a content type for the galaxy service"""
    content_type, _ = DABContentType.objects.get_or_create(
        service='galaxy',
        app_label='galaxy_test',
        model='collection_test',
        defaults={'api_slug': 'galaxy.collection_test', 'pk_field_type': 'integer', 'pk': 9000},
    )
    return content_type


@pytest.fixture
def controller_content_type():
    """Create a content type for the controller service"""
    content_type, _ = DABContentType.objects.get_or_create(
        service='controller',
        app_label='controller_test',
        model='project_test',
        defaults={'api_slug': 'controller.project_test', 'pk_field_type': 'integer', 'pk': 9002},
    )
    return content_type


@pytest.fixture
def galaxy_permission(galaxy_content_type):
    """Create a permission for the galaxy service"""
    permission, _ = DABPermission.objects.get_or_create(
        content_type=galaxy_content_type,
        codename='view_collection_test',
        defaults={'name': 'Can view collection test', 'api_slug': 'galaxy.view_collection_test'},
    )
    return permission


@pytest.fixture
def controller_permission(controller_content_type):
    """Create a permission for the controller service"""
    permission, _ = DABPermission.objects.get_or_create(
        content_type=controller_content_type,
        codename='view_project_test',
        defaults={'name': 'Can view project test', 'api_slug': 'controller.view_project_test'},
    )
    return permission


@pytest.fixture
def serializer():
    """Create a GatewayRoleDefinitionSerializer instance"""
    return GatewayRoleDefinitionSerializer()


@pytest.mark.django_db
class TestRoleDefinitionValidation:
    """Tests for custom validation logic in GatewayRoleDefinitionViewSet

    Generated by Claude Code (claude-sonnet-4@20250514)
    """

    def test_system_role_with_galaxy_permissions_allowed(self, serializer, galaxy_permission):
        """Test that system roles with only galaxy permissions are allowed"""
        # Test data for a system role with galaxy permissions
        attrs = {
            'name': 'Galaxy System Role',
            'description': 'A system role for galaxy service',
            'content_type': None,  # This makes it a system role
            'permissions': [galaxy_permission],
        }

        # This should not raise an exception
        validated_attrs = serializer.validate(attrs)
        assert validated_attrs == attrs

    def test_system_role_with_non_galaxy_permissions_forbidden(self, serializer, controller_permission):
        """Test that system roles with non-galaxy permissions raise ValidationError"""
        # Test data for a system role with non-galaxy permissions
        attrs = {
            'name': 'Invalid System Role',
            'description': 'A system role with non-galaxy permissions',
            'content_type': None,  # This makes it a system role
            'permissions': [controller_permission],
        }

        # This should raise a ValidationError
        with pytest.raises(ValidationError) as exc_info:
            serializer.validate(attrs)

        assert "System roles can only have permissions for the 'galaxy' service" in str(exc_info.value)
        assert "Invalid permissions:" in str(exc_info.value)
        assert "view_project_test" in str(exc_info.value)
        assert "service: controller" in str(exc_info.value)

    def test_system_role_with_mixed_permissions_forbidden(self, serializer, galaxy_permission, controller_permission):
        """Test that system roles with mixed galaxy and non-galaxy permissions are forbidden"""
        # Test data for a system role with mixed permissions
        attrs = {
            'name': 'Mixed System Role',
            'description': 'A system role with mixed permissions',
            'content_type': None,  # This makes it a system role
            'permissions': [galaxy_permission, controller_permission],
        }

        # This should raise a ValidationError because of the non-galaxy permission
        with pytest.raises(ValidationError) as exc_info:
            serializer.validate(attrs)

        assert "System roles can only have permissions for the 'galaxy' service" in str(exc_info.value)
        assert "Invalid permissions:" in str(exc_info.value)
        assert "view_project_test" in str(exc_info.value)
        assert "service: controller" in str(exc_info.value)

    def test_non_system_role_with_galaxy_permissions_allowed(self, serializer, galaxy_content_type, galaxy_permission):
        """Test that non-system roles (with content_type) skip system role validation"""
        # Test data for a non-system role with galaxy permissions
        attrs = {
            'name': 'Galaxy Object Role',
            'description': 'An object-level role for galaxy service',
            'content_type': galaxy_content_type,  # This makes it a non-system role
            'permissions': [galaxy_permission],  # Use galaxy permission for galaxy content type
        }

        # This should not raise an exception because it's not a system role
        # (The parent serializer handles content_type-specific permission validation)
        validated_attrs = serializer.validate(attrs)
        assert validated_attrs == attrs

    def test_system_role_with_multiple_invalid_permissions(self, serializer, controller_permission):
        """Test that system roles with multiple invalid permissions report all of them"""
        # Create a second controller permission
        from ansible_base.rbac.models import DABPermission

        controller_permission2, _ = DABPermission.objects.get_or_create(
            content_type=controller_permission.content_type,
            codename='change_project_test',
            defaults={'name': 'Can change project test', 'api_slug': 'controller.change_project_test'},
        )

        # Test data for a system role with multiple invalid permissions
        attrs = {
            'name': 'Multiple Invalid System Role',
            'description': 'A system role with multiple invalid permissions',
            'content_type': None,  # This makes it a system role
            'permissions': [controller_permission, controller_permission2],
        }

        # This should raise a ValidationError listing both invalid permissions
        with pytest.raises(ValidationError) as exc_info:
            serializer.validate(attrs)

        error_message = str(exc_info.value)
        assert "System roles can only have permissions for the 'galaxy' service" in error_message
        assert "Invalid permissions:" in error_message
        assert "view_project_test" in error_message
        assert "change_project_test" in error_message
        assert "service: controller" in error_message


@pytest.mark.django_db
class TestRoleDefinitionAPIValidation:
    """API tests for role definition validation logic

    Generated by Claude Code (claude-sonnet-4@20250514)
    """

    def test_api_create_system_role_with_galaxy_permissions_allowed(self, admin_api_client, galaxy_permission):
        """Test creating system role with galaxy permissions via API succeeds"""
        data = {
            'name': 'Galaxy System Role API',
            'description': 'A system role for galaxy service created via API',
            'content_type': None,  # System role
            'permissions': [galaxy_permission.api_slug],
        }

        response = admin_api_client.post(get_relative_url('roledefinition-list'), data, format='json')
        assert response.status_code == 201, response.data

    def test_api_create_system_role_with_non_galaxy_permissions_forbidden(self, admin_api_client, controller_permission):
        """Test creating system role with non-galaxy permissions via API fails"""
        data = {
            'name': 'Invalid System Role API',
            'description': 'A system role with non-galaxy permissions created via API',
            'content_type': None,  # System role
            'permissions': [controller_permission.api_slug],
        }

        response = admin_api_client.post(get_relative_url('roledefinition-list'), data, format='json')
        assert response.status_code == 400, response.data
        assert "System roles can only have permissions for the 'galaxy' service" in str(response.data)
        assert "Invalid permissions:" in str(response.data)
        assert "view_project_test" in str(response.data)
        assert "service: controller" in str(response.data)

        # Verify the role definition was not created in the database
        assert not RoleDefinition.objects.filter(name='Invalid System Role API').exists()

    def test_api_create_system_role_with_mixed_permissions_forbidden(self, admin_api_client, galaxy_permission, controller_permission):
        """Test creating system role with mixed galaxy and non-galaxy permissions via API fails"""
        data = {
            'name': 'Mixed System Role API',
            'description': 'A system role with mixed permissions created via API',
            'content_type': None,  # System role
            'permissions': [galaxy_permission.api_slug, controller_permission.api_slug],
        }

        response = admin_api_client.post(get_relative_url('roledefinition-list'), data, format='json')
        assert response.status_code == 400, response.data
        assert "System roles can only have permissions for the 'galaxy' service" in str(response.data)
        assert "Invalid permissions:" in str(response.data)
        assert "view_project_test" in str(response.data)
        assert "service: controller" in str(response.data)

        # Verify the role definition was not created in the database
        assert not RoleDefinition.objects.filter(name='Mixed System Role API').exists()

    def test_api_create_non_system_role_with_any_permissions_allowed(self, admin_api_client, galaxy_content_type, galaxy_permission):
        """Test creating non-system role with any permissions via API succeeds"""
        data = {
            'name': 'Galaxy Object Role API',
            'description': 'An object-level role for galaxy service created via API',
            'content_type': galaxy_content_type.api_slug,  # Non-system role
            'permissions': [galaxy_permission.api_slug],
        }

        response = admin_api_client.post(get_relative_url('roledefinition-list'), data, format='json')
        assert response.status_code == 201, response.data

    def test_api_patch_system_role_with_invalid_permissions(self, admin_api_client, galaxy_permission, controller_permission):
        """Test PATCH with invalid permissions returns 400 and preserves original permissions"""
        # First create a valid system role
        role_definition = RoleDefinition.objects.create(
            name='Galaxy System Role PATCH Test', description='A system role for PATCH testing', content_type=None  # System role
        )
        role_definition.permissions.add(galaxy_permission)

        # Try to PATCH with invalid permissions
        data = {'permissions': [controller_permission.api_slug]}

        response = admin_api_client.patch(get_relative_url('roledefinition-detail', kwargs={'pk': role_definition.id}), data, format='json')

        # Verify validation prevents the invalid change
        assert response.status_code == 400, response.data
        assert "System roles can only have permissions for the 'galaxy' service" in str(response.data)
        assert "Invalid permissions:" in str(response.data)
        assert "view_project_test" in str(response.data)
        assert "service: controller" in str(response.data)

        # Verify original permissions are preserved (not corrupted by invalid update attempt)
        role_definition.refresh_from_db()
        assert list(role_definition.permissions.all()) == [galaxy_permission]


@pytest.mark.django_db
class TestManagedRoleDefinitionValidation:
    """Tests for managed role definition validation - demonstrating bug where managed roles can still be edited

    Generated by Claude Sonnet 4
    """

    def test_managed_role_definition_update_should_return_400(self, admin_api_client, galaxy_permission):
        """Test that updating a managed role definition should return 400 error (currently failing due to bug)"""
        # Create a managed role definition
        role_definition = RoleDefinition.objects.create(
            name='Managed Test Role',
            description='A managed role that should not be editable',
            content_type=None,  # System role
            managed=True,  # This makes it managed by the system
        )
        role_definition.permissions.add(galaxy_permission)

        # Try to update the managed role definition - this should fail with 400
        data = {'name': 'Updated Managed Role Name', 'description': 'This update should be rejected'}

        response = admin_api_client.patch(get_relative_url('roledefinition-detail', kwargs={'pk': role_definition.id}), data, format='json')

        # This assertion will currently FAIL due to the bug - managed roles can still be edited
        assert response.status_code == 400, f"Expected 400 error for managed role edit, got {response.status_code}: {response.data}"

    def test_managed_role_definition_delete_should_return_400(self, admin_api_client, galaxy_permission):
        """Test that deleting a managed role definition should return 400 error (currently failing due to bug)"""
        # Create a managed role definition
        role_definition = RoleDefinition.objects.create(
            name='Managed Test Role for Delete',
            description='A managed role that should not be deletable',
            content_type=None,  # System role
            managed=True,  # This makes it managed by the system
        )
        role_definition.permissions.add(galaxy_permission)

        # Try to delete the managed role definition - this should fail with 400
        response = admin_api_client.delete(get_relative_url('roledefinition-detail', kwargs={'pk': role_definition.id}))

        # This assertion will currently FAIL due to the bug - managed roles can still be deleted
        assert response.status_code == 400, f"Expected 400 error for managed role delete, got {response.status_code}: {response.data}"

    def test_unmanaged_role_definition_update_should_succeed(self, admin_api_client, galaxy_permission):
        """Test that updating an unmanaged role definition should succeed (control test)"""
        # Create an unmanaged role definition
        role_definition = RoleDefinition.objects.create(
            name='Unmanaged Test Role',
            description='An unmanaged role that should be editable',
            content_type=None,  # System role
            managed=False,  # This makes it unmanaged, so editable
        )
        role_definition.permissions.add(galaxy_permission)

        # Try to update the unmanaged role definition - this should succeed
        data = {'name': 'Updated Unmanaged Role Name', 'description': 'This update should be allowed'}

        response = admin_api_client.patch(get_relative_url('roledefinition-detail', kwargs={'pk': role_definition.id}), data, format='json')

        # This should succeed for unmanaged roles
        assert response.status_code == 200, f"Expected 200 for unmanaged role edit, got {response.status_code}: {response.data}"
        assert response.data['name'] == 'Updated Unmanaged Role Name'
