# Generated by Django 4.2.21 on 2025-09-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aap_gateway_api', '0014_add_last_login_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='MigrateServiceDataHasRan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_ran', models.BooleanField(default=False, help_text='True if migrate_service_data has completed successfully, False otherwise')),
            ],
            options={
                'verbose_name': 'Migrate Service Data Flag',
                'verbose_name_plural': 'Migrate Service Data Flags',
            },
        ),
    ]
