# Generated by Django 4.2.22 on 2025-10-08 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aap_gateway_api', '0015_migrateservicedatahasran'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='enable_mtls',
            field=models.BooleanField(default=False, help_text='If true, the route requires mutual TLS. Connecting clients have to provide one or more certificates.'),
        ),
        migrations.CreateModel(
            name='CACertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True, help_text='The date/time this resource was created.')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date/time this resource was created.')),
                ('name', models.CharField(help_text='The name of this resource.', max_length=512, unique=True)),
                ('pem_data', models.TextField(help_text='Certificate content in PEM format')),
                ('sha256', models.CharField(help_text='SHA256 signature of pem_data', max_length=64)),
                ('related_id_reference', models.CharField(blank=True, help_text='Reference to an object that is related to this CA.', max_length=64)),
                ('created_by', models.ForeignKey(default=None, editable=False, help_text='The user who created this resource.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(default=None, editable=False, help_text='The user who last modified this resource.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
