# Generated by Django - remove use_controller_password (AAP 2.7+, Controller fallback removed)

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aap_gateway_api', '0018_remove_controller_fallback_from_local_authenticators'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='use_controller_password',
        ),
    ]
