# Generated by Django 5.2.9 on 2026-04-28 13:19

from django.db import migrations


def remove_runtime_feature_flags_ui_preference(apps, schema_editor):
    Preference = apps.get_model('aap_gateway_api', 'Preference')
    Preference.objects.filter(section='feature_flags', name='RUNTIME_FEATURE_FLAGS_UI').delete()


def restore_runtime_feature_flags_ui_preference(apps, schema_editor):
    import warnings

    warnings.warn(
        "Rolling back this migration will not restore the deleted preference: "
        "RUNTIME_FEATURE_FLAGS_UI. "
        "The preference library will recreate it with default values.",
        stacklevel=1,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("aap_gateway_api", "0020_route_request_timeout_seconds"),
    ]

    operations = [
        migrations.RunPython(
            remove_runtime_feature_flags_ui_preference,
            restore_runtime_feature_flags_ui_preference,
        ),
    ]
