---
gateway_host: https://localhost:8000
gateway_port: 8000
# If you are running on Linux you likely will want to change this port to 9043 or something else > 1024 if not running podman as root
proxy_port: 443
db_username: gateway
db_password: gateway
db_port: 5440
container_reference: localhost
# This is where to put all the docker source files relative to the tools/docker-compose/ansible directory
sources_dest: '{{ playbook_dir | dirname }}/generated'
docker_compose_cmd: "{{ lookup('ansible.builtin.env', 'DOCKER_COMPOSE', default='docker compose') }} -f {{ sources_dest }}/docker-compose.yml"

container_engine: docker
gateway_image: 'quay.io/ansible/aap-gateway:devel'
gateway_host_address: host-gateway
gateway_services: "{{ enabled_services | default([], true) }}"
gateway_container_name: aap_gw_1

ddt_enabled: "{{ enable_django_debug_toolbar | default(False) }}"

enabled_containers:
  keycloak: "{{ keycloak_enabled | default(False) }}"
  ldap: "{{ ldap_enabled | default(False) }}"
  tacacs: "{{ tacacs_enabled | default(False) }}"
  radius: "{{ radius_enabled | default(False) }}"
  haproxy: "{{ haproxy_enabled | default(False) }}"

# Redis settings
redis_mode_options:
  - standalone
  - sentinel
  - cluster
redis_node_topology_count:
  standalone: 1
  sentinel: 1
  cluster: 6
redis_sentinel_replica_nodes: 1
redis_sentinel_sentinel_nodes: 3
redis_mode: "{{ redis_type | default(redis_mode_options[0]) }}"
redis_node_count: "{{ redis_node_topology_count[redis_mode] | default(1) }}"
redis_uses_tls: "{{ redis_tls_enabled | default(True) }}"
redis_node_prefix: 'aap_gw_redis_'
cache_key_prefix: 'gateway'

# Keycloak settings
keycloak_exposed_port: 8443
keycloak_image: quay.io/keycloak/keycloak
keycloak_image_version: 15.0.2
keycloak_username: admin
keycloak_password: admin
cert_subject: "/C=US/ST=NC/L=Durham/O=gateway/CN=devenv"
oidc_reference:

# LDAP docker compose settings
ldap_exposed_ldap_port: 389
ldap_exposed_ldaps_port: 636
ldap_image_version: latest
ldap_admin_username: admin
ldap_admin_password: admin
ldap_public_key_file_name: 'ldap.cert'
ldap_private_key_file_name: 'ldap.key'

# Tacacs plus
tacacs_container_version: latest
tacacs_exposed_tacacs_port: 49

# RADIUS
radius_image: "mirror.gcr.io/freeradius/freeradius-server"
radius_image_version: latest

# Redis
redis_container_version: latest
redis_exposed_port: 6380
redis_username: gateway1
redis_password: redis_password
redis_sentinel_username: redis_sentinel_username
redis_sentinel_password: redis_sentinel_password

# HAProxy
proxy_container_version: latest
