---
- name: Generate Redis cert subjectAltName and clustered host list
  set_fact:
    sans: "{{ sans | default([]) + [host_sans] }}"
    redis_hosts: "{{ redis_hosts | default([]) + [ host_port ] }}"
  loop: "{{ query('sequence', 'start=1 end='+(redis_node_count)|string) }}"
  vars:
    hostname: "{{ redis_node_prefix }}{{ item }}"
    host_sans: 'DNS:{{ hostname }}'
    host_port: "{{ hostname }}:{{ redis_exposed_port }}"

- name: Read requirements_git.txt
  slurp:
    src: "{{ sources_dest }}/../../requirements/requirements_git.txt"
  register: git_requirements

- name: Get the optional dependencies for DAB
  set_fact:
    optional_dab_deeps: "{{ item | regex_replace('^django-ansible-base\\[(.*)\\] @.*', '\\1') }}"
  when: "'django-ansible-base[' in item"
  loop: "{{ git_requirements['content'] | b64decode | split('\n') }}"
  loop_control:
    label: 'reading line'

- name: Render docker templates
  template:
    src: "{{ item }}.j2"
    dest: "{{ sources_dest }}/{{ item }}"
    mode: '0666'
  loop:
    - docker-compose.yml
    - docker-compose-stage.yml
    - Dockerfile
    - haproxy.cfg

- name: Initialize Redis
  include_tasks:
    file: initialize_redis.yml
