---
gateway_host: https://localhost:8000
gateway_node_count: 1  # Envoy will be scaled equally with the number of gateway nodes
proxy_port: 443
gateway_validate_certs: False
gateway_admin_username: admin
gateway_admin_password: admin
container_reference: 'localhost'
# This is the delay between envoy refreshing the xDS configuration
xds_refresh_delay_seconds: 60
# enable_django_debug_toolbar: True

# What services are enabled in your local environment
# Note: If you have a service specified but its not functional the UI will be broken
enabled_services:
  - 'hub'
  - 'controller'
  - 'eda'
  - 'lightspeed'

### Redis
### Note: If you change the redis settings, please remove tools/generated/redis_cluster and let it rebuild
# redis_type: # Possible options: standalone (default), sentinel, cluster
redis_tls_enabled: True

### Sidecars (uncomment to enable):
# haproxy_enabled: True
# keycloak_enabled: True
# ldap_enabled: True
# tacacs_enabled: True
# radius_enabled: True

### Gateway preferences that will be set
gateway_preferences:
  status_endpoint_backend_timeout_seconds: 10
  status_endpoint_backend_verify: false
