[uwsgi]
; Set buffer size higher than default 4kB to accommodate Azure AD
buffer-size=10240
socket = 127.0.0.1:8050
processes = 5
master = true
vacuum = true
no-orphans = true
lazy-apps = true
enable-threads = true
manage-script-name = true

harakiri = 10
harakiri-graceful-timeout = 2
harakiri-graceful-signal = 6
py-call-osafterfork = true

mount = /=aap_gateway_api.wsgi:application
log-format = [pid: %(pid)|app: -|req: -/-] %(addr) (%(user)) {%(vars) vars in %(pktsize) bytes} [%(ctime)] %(method) %(uri) => generated %(rsize) bytes in %(msecs) msecs (%(proto) %(status)) %(headers) headers in %(hsize) bytes (%(switches) switches on core %(core)) x-request-id: %(var.HTTP_X_REQUEST_ID)
