---
name: aap dev env tests
on: workflow_dispatch
jobs:
  aap-smoke:
    name: aap dev env smoke tests
    runs-on: ubuntu-latest
    env:
      HEADLESS: "yes"

    steps:
      - uses: actions/checkout@v4

      - name: Spin up the dev env
        run: cd aap-dev && make dev-up

      - name: Perform smoke tests
        run: cd aap-dev && make smoke
