# JUnit Upload Workflow for aap-gateway
#
# This workflow is triggered by the Unit Tests workflow completion.
#
# Steps overview:
# 1. Download JUnit results from Unit Tests workflow
# 2. Extract commit and repository information
# 3. Upload JUnit XML test results
#

name: JUnit Upload
on:
  workflow_run:
    workflows:
      - Unit Tests
    types:
      - completed
permissions: read-all
jobs:
  junit-upload:
    name: Upload JUnit XML test results
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'pull_request'
    steps:
      - uses: actions/checkout@v4

      # Download JUnit results from workflow_run
      - name: Download results artifact
        uses: dawidd6/action-download-artifact@246dbf436b23d7c49e21a7ab8204ca9ecd1fe615
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: Unit Tests
          run_id: ${{ github.event.workflow_run.id }}
          name: aap-gateway-test-results

      # Set COMMIT_SHA and REPO_NAME from workflow_run
      - name: Set COMMIT_SHA and REPO_NAME
        env:
          WORKFLOW_RUN_HEAD_SHA: ${{ github.event.workflow_run.head_sha }}
          WORKFLOW_RUN_REPO_NAME: ${{ github.event.repository.full_name }}
        run: |
          echo "COMMIT_SHA=$WORKFLOW_RUN_HEAD_SHA" >> $GITHUB_ENV
          echo "REPO_NAME=$WORKFLOW_RUN_REPO_NAME" >> $GITHUB_ENV

      - name: Upload jUnit XML test results
        run: >-
          curl -v --fail-with-body
          --user "${{ vars.PDE_ORG_RESULTS_AGGREGATOR_UPLOAD_USER }}:${{ secrets.PDE_ORG_RESULTS_UPLOAD_PASSWORD }}"
          --form "xunit_xml=@aap-gateway-test-results.xml"
          --form "component_name=aap-gateway"
          --form "git_commit_sha=${{ env.COMMIT_SHA }}"
          --form "git_repository_url=https://github.com/${{ env.REPO_NAME }}"
          "${{ vars.PDE_ORG_RESULTS_AGGREGATOR_UPLOAD_URL }}"
