---
name: Linting
env:
  LC_ALL: "C.UTF-8" # prevent ERROR: Ansible could not initialize the preferred locale: unsupported locale setting
on:
  pull_request:
  merge_group:
  push:
    branches:
      - devel
      - stable-*
jobs:
  ci-image-tag:
    uses: ./.github/workflows/ci-image-tag.yml
    with:
      ref: ${{ github.event.merge_group.base_ref || github.base_ref || github.ref_name }}

  common-tests:
    name: ${{ matrix.tests.name }}
    needs: ci-image-tag
    runs-on: ubuntu-latest
    container:
      image: quay.io/ansible/jewel-ci:${{ needs.ci-image-tag.outputs.tag }}
    permissions:
      packages: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        tests:
          - name: api-ruff-check
            command: check_ruff
          - name: api-ruff-format
            command: check_ruff_format
    steps:
      - uses: actions/checkout@v4

      - name: Run check ${{ matrix.tests.name }}
        run: make ${{ matrix.tests.command }}
