---
name: Smoke-test dev env
on:
  push:
    branches:
      - devel  # This prevents annoying failure emails from pushing to feature branches on forks
  pull_request:
jobs:
  smoke-test:
    name: smoke-test dev env
    runs-on: ubuntu-latest
    env:
      HEADLESS: "yes"
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.GITHUB_SHA }}

      - name: Checkout DAB branch if needed
        env:
          PR_BODY: ${{ github.event.pull_request.body }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: tools/scripts/get_dab_for_pr.py

      - name: Install python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Upgrade ansible-core
        run: pip3.11 install --upgrade ansible-core

      - name: Start the dev environment
        run: COMPOSE_UP_OPTS='-d' make docker-compose

      - name: Try out the dev env
        run: |
          ansible-playbook -v tools/ansible/smoke-test.yml \
            -e repo_root=$(pwd) \
            -e gateway_vars=$(readlink -f container-startup.yml) \
            --skip-tags start_dev_environment,dump_container_logs

      - name: Dump the container logs on failure
        run: docker compose -f tools/generated/docker-compose.yml logs
        if: failure()
